allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  puppeteer: true
  sharp: true
  vue-demi: true
  workerd: true
minimumReleaseAgeExclude:
  - imagetools-core@11.0.0
  - vite-imagetools@11.0.0
